site_name: Colisiones de discos en un espacio limitado

nav:
  - Problema: index.md
  - Metodología: explanation.md
  - Ejemplos de uso: tutorial.md
  - Recursos de implementación: reference.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - mkdocstrings

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js 
    
theme:
  name: "material"
