site_name: Colisiones de discos en un espacio limitado

nav:
  - Inicio: index.md
  - Explicaci√≥n: explanation.md
  - Tutorial: tutorial.md
  - Referencia: reference.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight

plugins:
  - mkdocstrings

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: material
