site_name: Colisiones de discos en un espacio limitado

nav:
  - Inicio: index.md
  - Explicaci√≥n: explanation.md
  - Tutorial: tutorial.md
  - Referencia: reference.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

plugins:
  - mkdocstrings

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js

theme: material
